version: '3'
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  jenkins_data:

services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
       - jenkins_data:/var/jenkins_home
    networks:
      - cicd
    ports:
      - '8080:8080'
      - '50000:50000'
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: zap
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true
    networks:
      - cicd
    expose:
      - 8080
    ports:
      - '8085:8080'

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - cicd
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - '9000:9000'
    expose:
      - 9000

  myapp:
    image: jtux/spring-boot-demo
    container_name: myapp
    networks:
      - cicd
    expose:
      - 8080

networks:
  cicd:
    driver: bridge
